version: "3.7"

services:

  # This is the Mosquitto MQTT broker
  mosquitto:
    image: eclipse-mosquitto:2.0.10
    restart: unless-stopped
    volumes:
        - ./configs/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
    networks:
      - backend

  nodered:
    build: ./nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    networks:
      - backend
    volumes:
      - nodered-storage:/data
      
volumes:
  nodered-storage:

networks:
  backend: