version: "3.7"

# All the environment variables are bundled in .env which is automatically included when running this with docker-compose. This has the big advantage that you only need to specify the information in 1 file and have only a single place of truth.
# The information is then passed to the correct service in this docker-compose file.

services:

  # This is the Mosquitto MQTT broker
  mqtt:
    image: eclipse-mosquitto:2.0.10
    restart: unless-stopped
    volumes:
        - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
    networks:
      - backend

  # This is the NodeRED instance
  nodered:
    build: ./nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    depends_on:
      - influxdb
      - mqtt
    networks:
      - backend
    volumes:
      - nodered-storage:/data

  # This is the InfluxDB time series database
  influxdb:
    image: influxdb:1.8.4
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      INFLUXDB_DB: cdem

  # This is the Grafana dashboard service
  grafana:
    image: grafana/grafana:7.5.7
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    networks:
      - backend
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  nodered-storage:
  influxdb:
  grafana-storage:

networks:
  backend: